theme: jekyll-theme-minimal
title: Marcel's Space
description: Links and Collections
show_downloads: false
logo: https://0.gravatar.com/avatar/c8ede957dd07e97ac3e6cac22d1fa323?s=200
baseurl: ""
url: "https://tcm-marcel.github.io"
